### ISSUE TITLE
Errno::ESPIPE: Illegal seek @ rb_io_tell

### ISSUE THREAD

**Issue by pedrocunha** [SciRuby/packable#4]
Hi folks,

This seems to be throwing errors on Ruby 2.5 on a container running tests (CircleCI). This gem is being imported by NMatrix. 

```
Errno::ESPIPE: Illegal seek @ rb_io_tell - <STDERR>
  /usr/local/bundle/gems/packable-1.3.9/lib/packable/extensions/io.rb:86:in `pos'
  /usr/local/bundle/gems/packable-1.3.9/lib/packable/extensions/io.rb:86:in `pack_and_write'
  /usr/local/bundle/gems/packable-1.3.9/lib/packable/extensions/io.rb:62:in `write_with_packing'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:81:in `abort'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:81:in `rescue in kernel_load'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:65:in `kernel_load'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:424:in `exec'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
  /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
  /usr/local/bundle/bin/bundle:23:in `load'
  /usr/local/bundle/bin/bundle:23:in `<main>'
```

When I run locally I get no errors. So I am not sure where to look. 

### Environment

```
Bundler       1.16.2
  Platforms   ruby, x86_64-linux
Ruby          2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      2.7.7
  Gem Home    /usr/local/bundle
  Gem Path    
  User Path   /app/.gem/ruby/2.5.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.0.1t  3 May 2016
  Loaded      OpenSSL 1.0.1t  3 May 2016
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.1.4
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

Any suggestions? Thanks

**Comment by boutil** [comment]
This also occurs in Debian,
see the report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888164

**Comment by patleb** [comment]
Would be nice to have it work for Ruby 2.5

**Comment by Amval** [comment]
I was going to also report a bug on NMatrix before I saw this. Ubuntu 18.04, ruby 2.5.1 through rbenv. It seems to mess with the file system somehow.

As this triggers the error:
```
require 'nmatrix'
p __FILE__
```
`File.read` works, but using the standard CSV library fails (`CSV.foreach` does nothing if I import `nmatrix`). I am going to try and see what happens with a different (lower) ruby version.

**Comment by gbrlcustodio** [comment]
I'm facing the same error. Is this project still being maintained?

**Comment by marcandre** [comment]
I'll try and have a look tomorrow.

**Comment by marcandre** [comment]
Here's an update.
`packable` is code I wrote 9 years ago for Ruby 1.8 and it shows.
It monkeypatches `String#pack` and `Array#unpack` which is not the best idea, and`IO#each/read/write` which is a worse idea.
At least `IO#write` is potentially incompatible now as the monkeypatch uses the number of argument to know which version to use (used to be 1 for builtin, but now is variable).
I can't install `nmatrix` on my macs because of compiler issues I'm not willing to deal with (see multiple issues).
I released 1.3.10 that fixes some detection for the monkeypatches, but I can't test if that resolves the issue or not. If anyone has a way to reproduce the error that doesn't involve installing `nmatrix` let me know.
If anyone wants to sponsor me for a v2 of packable (without monkeypatches), let me know too ;-)

**Comment by gbrlcustodio** [comment]
Thanks @marcandre for the work, but, at least for me, the problem still happening with the latest version of packable, ruby and nmatrix. Besides downgrading ruby, witch I would prefer not to, is there an alternative fix?

**Comment by marcandre** [comment]
Sorry it didn't help, @gbrlcustodio 😢 

Without knowing more about what is actually going on, it's though to point to an alternative fix.

**Comment by Uditgulati** [comment]
The error can be reproduced with
```
require 'packable'
p 1
```
Here's output for same https://pastebin.com/TqnWvERs

**Comment by marcandre** [comment]
I still can't reproduce it.

```
[~/packable(master)]$ ruby -I ./lib -e "require 'packable'; p 1"
1
```

**Comment by marcandre** [comment]
No issue on Mac OS...

**Comment by pocheptsov** [comment]
Hi @marcandre you can reproduce it in docker env with:

`$ docker run -v $(pwd):/home -w /home -it ruby:2.5.5-alpine3.9 sh -c 'apk add git; bundle install; ruby -I ./lib -e "require \"packable\"; p 1"'`

```
Traceback (most recent call last):
        4: from -e:1:in `<main>'
        3: from -e:1:in `p'
        2: from /home/lib/packable/extensions/io.rb:62:in `write_with_packing'
        1: from /home/lib/packable/extensions/io.rb:86:in `pack_and_write'
/home/lib/packable/extensions/io.rb:86:in `pos': Invalid seek @ rb_io_tell - <STDOUT> (Errno::ESPIPE)
```

or any higher version

`$ docker run -v $(pwd):/home -w /home -it ruby:2.6.2-alpine3.9 sh -c 'apk add git; bundle install; ruby -I ./lib -e "require \"packable\"; p 1"'`

I will try to dig deeped to the cause of this issue also suspect that it's related to [`IO#writev` release](https://bugs.ruby-lang.org/issues/9323).

**Comment by pocheptsov** [comment]
After adding a check on `tty?` fixed issue for me, not sure if that's the right comprehensive solution:

```
      def each_with_packing(*options, &block)
        return each_without_packing(*options, &block) if (Integer === options.first) || (String === options.first) || tty?
        return Enumerator.new(self, :each_with_packing, *options) unless block_given?
        yield read(*options) until eof?
      end

      def write_with_packing(*arg)
        (arg.length == 1 || tty?) ? write_without_packing(*arg) : pack_and_write(*arg)
      end
      def read_with_packing(*arg)
        return read_without_packing(*arg) if arg.length == 0 || arg.first.nil? || arg.first.is_a?(Numeric) || tty?
      ...
```

**Comment by kojix2** [comment]
Thank you @pocheptsov.
I do not know the details well, but I confirmed that it works on my PC.
This issue is an obstacle to releasing a new version of Daru. 
I am very happy if this problem is solved.

**Comment by kojix2** [comment]
@v0dro 
@Shekharrajak
Do you want to merge this pull request so that Daru's tests can run on Ruby 2.6?

**Comment by marcandre** [comment]
Hopefully v1.3.11 will fix this for everyone and someone will provide a PR to use refinements instead...
